
### Request kID information
GET http://localhost:8080/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJLSUQiOiIiLCJpYXQiOjE3MDg4OTkxOTIsImV4cCI6MTcwODg5OTIwN30.P9z11prgk5AQiDXjKLqH5xOAsW48RPKRTMmhrlqMrmg





### Get Auth token
POST http://localhost:8080/auth
Content-Type: application/json

{
    "user" : ""
}