
### Request kID information
GET http://localhost:8080/kID
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJLSUQiOiJib2IiLCJpYXQiOjE3MDg4OTY3MTUsImV4cCI6MTcwODg5NjczMH0.fse_9pzRPnEdDpiqt_8A9GQW07Wju3Cv1CWa1ygWBL0






### Get Auth token
POST http://localhost:8080/auth
Content-Type: application/json

{
    "user" : ""
}